### ISSUE TITLE
Comment not recognized as a type

### ISSUE THREAD

**Issue by madelgj** [madelgj/memoryleak#4]
Inside class Answer, Comment is not recognized as a type.
`/Answer.hpp:20: error: ‘Comment’ does not name a type
     Comment* removeComment(const int &id);
     ^~~~~~~`
`/Answer.hpp:21: error: ‘Comment’ was not declared in this scope
     vector<Comment *> getComments() const;
            ^~~~~~~`

**Comment by DiegoGarciaX2** [comment]
Arreglado, se estaban incluyendo varias veces la misma clase
